//! Developer-facing parallelization advisor for `.tlscript`.
//!
//! The advisor reduces the usability cost of explicit parallel contracts by explaining why a
//! function is currently serial/main-thread-only and by suggesting a safe starting decorator set.
//! It intentionally complements (not replaces) the strict [`super::parallel_hook`] validator.

use std::collections::{HashMap, HashSet};

use super::ast::{
    Block, DecoratorArg, DecoratorKind, Expr, ExprKind, FunctionDef, Item, Module, Stmt,
};
use super::parallel_hook::{
    ParallelFunctionHook, ParallelHookError, ParallelHookErrorKind, ParallelHookOutcome,
};
use super::semantic::{SemanticReport, SemanticType};
use super::token::Span;

/// High-level execution status reported by the advisor.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ParallelAdvisoryStatus {
    /// Function has a validated parallel contract and is eligible for MPS partitioning.
    ParallelReady,
    /// Function is explicitly constrained to the main thread.
    MainThreadOnly,
    /// Function currently falls back to serial execution.
    SerialFallback,
}

/// Why a function currently runs serially (or cannot be promoted automatically).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ParallelFallbackReason {
    /// No explicit parallel decorator was found.
    MissingParallelDecorator,
    /// Function is not exported, so runtime/MPS ABI dispatch is unavailable.
    MissingExportDecorator,
    /// A strict `@parallel` contract exists but failed validation.
    InvalidParallelContract,
    /// `@parallel(auto)` was requested but the advisor still needs explicit effect/domain info.
    AutoParallelNeedsContract,
    /// The function calls APIs that should stay on the main thread (UI/render/spawn/destroy class).
    MainThreadHostCalls,
    /// Host calls are unknown/non-annotated so safe parallelization cannot be inferred.
    UnknownHostCalls,
}

/// Actionable suggestion generated by the advisor.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ParallelAdvisorSuggestion {
    /// Add `@export` to allow MPS/WASM async dispatch.
    AddExport,
    /// Add `@main_thread` because the function uses UI/render/main-thread host APIs.
    AddMainThread,
    /// Add a starter parallel contract.
    AddParallelContract {
        /// Suggested decorator line (copy/paste friendly).
        decorator: String,
    },
    /// Replace `@parallel(auto)` with an explicit contract after reviewing inferred hints.
    ExpandAutoParallel {
        /// Suggested explicit decorator line.
        decorator: String,
    },
    /// Annotate/allowlist a host call so the compiler can reason about parallel safety.
    AnnotateHostCall {
        /// Host call name.
        name: String,
        /// Suggested classification.
        classification: &'static str,
    },
}

/// Per-function advisor report.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ParallelFunctionAdvice<'src> {
    /// Function name.
    pub function: &'src str,
    /// Function source span.
    pub span: Span,
    /// Current status.
    pub status: ParallelAdvisoryStatus,
    /// Fallback reason when `status == SerialFallback`.
    pub fallback_reason: Option<ParallelFallbackReason>,
    /// Whether a validated parallel hook is present.
    pub has_valid_parallel_contract: bool,
    /// Whether a validated main-thread hook is present.
    pub has_main_thread_contract: bool,
    /// Export status from semantic signatures.
    pub exported: bool,
    /// Host calls observed in the AST body (for diagnostics/tooling).
    pub observed_host_calls: Vec<&'src str>,
    /// Host calls classified as main-thread-only by advisor heuristics.
    pub main_thread_host_calls: Vec<&'src str>,
    /// Host calls not declared in module signatures (unknown/host boundary calls).
    pub unknown_host_calls: Vec<&'src str>,
    /// Parallel hook errors associated with this function (if any).
    pub parallel_hook_errors: Vec<ParallelHookErrorKind>,
    /// Actionable suggestions to improve parallelization or accessibility.
    pub suggestions: Vec<ParallelAdvisorSuggestion>,
}

/// Whole-module advisor output.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct ParallelAdvisorReport<'src> {
    /// Per-function advice in source order.
    pub functions: Vec<ParallelFunctionAdvice<'src>>,
    /// Total functions considered.
    pub function_count: usize,
    /// Number of functions ready for validated parallel dispatch.
    pub parallel_ready_count: usize,
    /// Number of functions pinned to main-thread execution.
    pub main_thread_count: usize,
    /// Number of functions currently serial fallback.
    pub serial_fallback_count: usize,
}

/// Source of a suggested parallel contract template.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ParallelContractTemplateSource {
    /// Generated for a serial function that has no explicit parallel contract.
    AddParallelContract,
    /// Generated to replace an invalid or incomplete `@parallel(auto)` contract.
    ExpandAutoParallel,
}

/// Copy/paste-friendly parallel contract suggestion extracted from advisor output.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ParallelContractTemplate<'src> {
    /// Function name the template applies to.
    pub function: &'src str,
    /// Suggested decorator source line.
    pub decorator: String,
    /// Why this template was generated.
    pub source: ParallelContractTemplateSource,
}

impl<'src> ParallelAdvisorReport<'src> {
    /// Compact human-readable summary line for logs/tooling panes.
    pub fn summary_line(&self) -> String {
        format!(
            "tlscript parallel advisor: total={} ready={} main_thread={} serial_fallback={}",
            self.function_count,
            self.parallel_ready_count,
            self.main_thread_count,
            self.serial_fallback_count
        )
    }

    /// Extract suggested parallel-contract templates from advisor suggestions.
    ///
    /// Tooling can present these as quick-fix actions for `@parallel(auto)` expansion or first-time
    /// parallelization.
    pub fn suggested_contract_templates(&self) -> Vec<ParallelContractTemplate<'src>> {
        let mut out = Vec::new();
        for func in &self.functions {
            for suggestion in &func.suggestions {
                match suggestion {
                    ParallelAdvisorSuggestion::AddParallelContract { decorator } => {
                        out.push(ParallelContractTemplate {
                            function: func.function,
                            decorator: decorator.clone(),
                            source: ParallelContractTemplateSource::AddParallelContract,
                        });
                    }
                    ParallelAdvisorSuggestion::ExpandAutoParallel { decorator } => {
                        out.push(ParallelContractTemplate {
                            function: func.function,
                            decorator: decorator.clone(),
                            source: ParallelContractTemplateSource::ExpandAutoParallel,
                        });
                    }
                    ParallelAdvisorSuggestion::AddExport
                    | ParallelAdvisorSuggestion::AddMainThread
                    | ParallelAdvisorSuggestion::AnnotateHostCall { .. } => {}
                }
            }
        }
        out
    }
}

/// Configuration for the parallel advisor heuristics.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ParallelAdvisorConfig {
    /// Host call names considered main-thread-only (UI/render/window/spawn-destroy class).
    pub main_thread_host_call_allowlist: Vec<String>,
    /// Domain used when generating starter `@parallel(...)` suggestions.
    pub default_parallel_domain: String,
    /// Default read effect list used in starter suggestions.
    pub default_read_effects: Vec<String>,
    /// Default write effect list used in starter suggestions.
    pub default_write_effects: Vec<String>,
    /// Default chunk hint for starter suggestions.
    pub default_chunk_hint: u16,
}

impl Default for ParallelAdvisorConfig {
    fn default() -> Self {
        Self {
            main_thread_host_call_allowlist: vec![
                "ui_".to_string(),
                "egui_".to_string(),
                "draw_".to_string(),
                "present".to_string(),
                "spawn_".to_string(),
                "destroy_".to_string(),
                "create_window".to_string(),
                "set_window_".to_string(),
                "wgpu_".to_string(),
                "renderer_".to_string(),
            ],
            default_parallel_domain: "entities".to_string(),
            default_read_effects: vec!["state".to_string()],
            default_write_effects: vec!["state".to_string()],
            default_chunk_hint: 256,
        }
    }
}

/// Heuristic advisor that explains serial fallback and suggests parallel contracts.
#[derive(Debug, Clone)]
pub struct ParallelAdvisor {
    config: ParallelAdvisorConfig,
}

impl ParallelAdvisor {
    /// Construct an advisor with explicit config.
    pub fn new(config: ParallelAdvisorConfig) -> Self {
        Self { config }
    }

    /// Build a module-level advisory report.
    pub fn analyze<'src>(
        &self,
        module: &Module<'src>,
        semantic: &SemanticReport<'src>,
        hooks: &ParallelHookOutcome<'src>,
    ) -> ParallelAdvisorReport<'src> {
        let hook_by_name: HashMap<&'src str, &ParallelFunctionHook<'src>> =
            hooks.functions.iter().map(|f| (f.function, f)).collect();
        let sig_by_name: HashMap<&'src str, _> =
            semantic.signatures.iter().map(|s| (s.name, s)).collect();

        let mut report = ParallelAdvisorReport::default();

        for item in &module.items {
            let Item::Function(func) = item;
            let exported = sig_by_name
                .get(func.name)
                .map(|s| s.exported)
                .unwrap_or(false);
            let hook = hook_by_name.get(func.name).copied();
            let parallel_errors = function_parallel_errors(func, hooks.errors.as_slice());
            let observed_calls = collect_function_calls(func);
            let module_fn_names: HashSet<&str> =
                semantic.signatures.iter().map(|s| s.name).collect();
            let unknown_host_calls: Vec<&'src str> = observed_calls
                .iter()
                .copied()
                .filter(|name| !module_fn_names.contains(*name))
                .collect();
            let main_thread_calls: Vec<&'src str> = observed_calls
                .iter()
                .copied()
                .filter(|name| self.is_main_thread_host_call(name))
                .collect();

            let mut advice = ParallelFunctionAdvice {
                function: func.name,
                span: func.span,
                status: ParallelAdvisoryStatus::SerialFallback,
                fallback_reason: Some(ParallelFallbackReason::MissingParallelDecorator),
                has_valid_parallel_contract: false,
                has_main_thread_contract: false,
                exported,
                observed_host_calls: observed_calls,
                main_thread_host_calls: unique_preserve_order(main_thread_calls),
                unknown_host_calls: unique_preserve_order(unknown_host_calls),
                parallel_hook_errors: parallel_errors.iter().map(|e| e.kind.clone()).collect(),
                suggestions: Vec::new(),
            };

            if let Some(h) = hook {
                match h.policy {
                    super::parallel_hook::ParallelExecutionPolicy::ParallelSafe => {
                        advice.status = ParallelAdvisoryStatus::ParallelReady;
                        advice.fallback_reason = None;
                        advice.has_valid_parallel_contract = true;
                    }
                    super::parallel_hook::ParallelExecutionPolicy::MainThreadOnly => {
                        advice.status = ParallelAdvisoryStatus::MainThreadOnly;
                        advice.fallback_reason = None;
                        advice.has_main_thread_contract = true;
                    }
                }
            } else {
                self.populate_serial_fallback_advice(func, &mut advice, parallel_errors.as_slice());
            }

            match advice.status {
                ParallelAdvisoryStatus::ParallelReady => report.parallel_ready_count += 1,
                ParallelAdvisoryStatus::MainThreadOnly => report.main_thread_count += 1,
                ParallelAdvisoryStatus::SerialFallback => report.serial_fallback_count += 1,
            }
            report.functions.push(advice);
        }

        report.function_count = report.functions.len();
        report
    }

    fn populate_serial_fallback_advice<'src>(
        &self,
        func: &FunctionDef<'src>,
        advice: &mut ParallelFunctionAdvice<'src>,
        parallel_errors: &[&ParallelHookError],
    ) {
        let requested_parallel_auto = function_requests_parallel_auto(func);

        if !parallel_errors.is_empty() {
            advice.fallback_reason = Some(if requested_parallel_auto {
                ParallelFallbackReason::AutoParallelNeedsContract
            } else {
                ParallelFallbackReason::InvalidParallelContract
            });

            if requested_parallel_auto {
                advice
                    .suggestions
                    .push(ParallelAdvisorSuggestion::ExpandAutoParallel {
                        decorator: self.build_parallel_decorator_suggestion(
                            Some(self.infer_domain(func)),
                            Some(self.infer_read_effects(func)),
                            Some(self.infer_write_effects(func)),
                        ),
                    });
            }
            return;
        }

        if !advice.exported {
            advice.fallback_reason = Some(ParallelFallbackReason::MissingExportDecorator);
            advice
                .suggestions
                .push(ParallelAdvisorSuggestion::AddExport);
        }

        if !advice.main_thread_host_calls.is_empty() {
            advice.fallback_reason = Some(ParallelFallbackReason::MainThreadHostCalls);
            advice
                .suggestions
                .push(ParallelAdvisorSuggestion::AddMainThread);
            for &name in &advice.main_thread_host_calls {
                advice
                    .suggestions
                    .push(ParallelAdvisorSuggestion::AnnotateHostCall {
                        name: name.to_string(),
                        classification: "main_thread_only",
                    });
            }
            return;
        }

        if !advice.unknown_host_calls.is_empty() {
            advice.fallback_reason = Some(ParallelFallbackReason::UnknownHostCalls);
            for &name in &advice.unknown_host_calls {
                advice
                    .suggestions
                    .push(ParallelAdvisorSuggestion::AnnotateHostCall {
                        name: name.to_string(),
                        classification: "parallel_safe or main_thread_only",
                    });
            }
        } else {
            advice.fallback_reason = Some(ParallelFallbackReason::MissingParallelDecorator);
        }

        let read = self.infer_read_effects(func);
        let write = self.infer_write_effects(func);
        let domain = self.infer_domain(func);
        advice
            .suggestions
            .push(ParallelAdvisorSuggestion::AddParallelContract {
                decorator: self.build_parallel_decorator_suggestion(
                    Some(domain),
                    Some(read),
                    Some(write),
                ),
            });
    }

    fn infer_domain<'src>(&self, func: &FunctionDef<'src>) -> &'src str {
        let name = func.name;
        if name.contains("particle") {
            "particles"
        } else if name.contains("body") || name.contains("physics") || name.contains("solve") {
            "bodies"
        } else if name.contains("chunk") {
            "chunks"
        } else {
            // Fallback to a static common domain token. (Borrowed literal avoids allocation.)
            "entities"
        }
    }

    fn infer_read_effects<'src>(&self, func: &FunctionDef<'src>) -> Vec<&'src str> {
        let mut out = Vec::new();
        if func.name.contains("physics") || func.name.contains("solve") {
            out.push("transform");
            out.push("force");
        } else if func.name.contains("particle") {
            out.push("position");
            out.push("velocity");
        } else {
            out.push("state");
        }
        out
    }

    fn infer_write_effects<'src>(&self, func: &FunctionDef<'src>) -> Vec<&'src str> {
        if func.name.contains("solve") {
            vec!["velocity"]
        } else if func.name.contains("integrate") {
            vec!["transform"]
        } else if func.name.contains("particle") {
            vec!["position"]
        } else {
            vec!["state"]
        }
    }

    fn build_parallel_decorator_suggestion(
        &self,
        domain: Option<&str>,
        read: Option<Vec<&str>>,
        write: Option<Vec<&str>>,
    ) -> String {
        let domain = domain.unwrap_or(self.config.default_parallel_domain.as_str());

        let read_joined = if let Some(read) = read {
            if read.is_empty() {
                self.config.default_read_effects.join(",")
            } else {
                read.join(",")
            }
        } else {
            self.config.default_read_effects.join(",")
        };
        let write_joined = if let Some(write) = write {
            if write.is_empty() {
                self.config.default_write_effects.join(",")
            } else {
                write.join(",")
            }
        } else {
            self.config.default_write_effects.join(",")
        };

        format!(
            "@parallel(domain=\"{}\", read=\"{}\", write=\"{}\", chunk={}, schedule=\"auto\")",
            domain, read_joined, write_joined, self.config.default_chunk_hint
        )
    }

    fn is_main_thread_host_call(&self, name: &str) -> bool {
        self.config
            .main_thread_host_call_allowlist
            .iter()
            .any(|pattern| {
                if pattern.ends_with('_') {
                    name.starts_with(pattern)
                } else {
                    name == pattern || name.contains(pattern)
                }
            })
    }
}

impl Default for ParallelAdvisor {
    fn default() -> Self {
        Self::new(ParallelAdvisorConfig::default())
    }
}

fn function_parallel_errors<'src, 'err>(
    func: &FunctionDef<'src>,
    errors: &'err [ParallelHookError],
) -> Vec<&'err ParallelHookError> {
    errors
        .iter()
        .filter(|e| span_is_within(e.span, func.span))
        .collect()
}

fn span_is_within(inner: Span, outer: Span) -> bool {
    inner.start >= outer.start && inner.end <= outer.end
}

fn function_requests_parallel_auto(func: &FunctionDef<'_>) -> bool {
    func.decorators.iter().any(|d| {
        matches!(d.kind, DecoratorKind::Named("parallel"))
            && d.args
                .iter()
                .any(|arg| matches!(arg, DecoratorArg::Flag { name: "auto", .. }))
    })
}

fn collect_function_calls<'src>(func: &FunctionDef<'src>) -> Vec<&'src str> {
    let mut out = Vec::new();
    collect_block_calls(&func.body, &mut out);
    unique_preserve_order(out)
}

fn collect_block_calls<'src>(block: &Block<'src>, out: &mut Vec<&'src str>) {
    for stmt in &block.statements {
        match stmt {
            Stmt::Let(s) => collect_expr_calls(&s.value, out),
            Stmt::Assign(s) => collect_expr_calls(&s.value, out),
            Stmt::If(s) => {
                for branch in &s.branches {
                    collect_expr_calls(&branch.condition, out);
                    collect_block_calls(&branch.body, out);
                }
                if let Some(b) = &s.else_block {
                    collect_block_calls(b, out);
                }
            }
            Stmt::While(s) => {
                collect_expr_calls(&s.condition, out);
                collect_block_calls(&s.body, out);
            }
            Stmt::ForRange(s) => {
                for arg in &s.range.args {
                    collect_expr_calls(arg, out);
                }
                collect_block_calls(&s.body, out);
            }
            Stmt::Expr(s) => collect_expr_calls(&s.expr, out),
        }
    }
}

fn collect_expr_calls<'src>(expr: &Expr<'src>, out: &mut Vec<&'src str>) {
    match &expr.kind {
        ExprKind::Unary { expr, .. } => collect_expr_calls(expr, out),
        ExprKind::Binary { left, right, .. } => {
            collect_expr_calls(left, out);
            collect_expr_calls(right, out);
        }
        ExprKind::Call { callee, args } => {
            if let ExprKind::Identifier(name) = callee.kind {
                out.push(name);
            }
            collect_expr_calls(callee, out);
            for arg in args {
                collect_expr_calls(arg, out);
            }
        }
        ExprKind::Grouping(inner) => collect_expr_calls(inner, out),
        ExprKind::Identifier(_)
        | ExprKind::IntegerLiteral(_)
        | ExprKind::FloatLiteral(_)
        | ExprKind::BoolLiteral(_)
        | ExprKind::StringLiteral(_) => {}
    }
}

fn unique_preserve_order<T>(items: Vec<T>) -> Vec<T>
where
    T: Eq + std::hash::Hash + Copy,
{
    let mut seen = HashSet::new();
    let mut out = Vec::with_capacity(items.len());
    for item in items {
        if seen.insert(item) {
            out.push(item);
        }
    }
    out
}

/// Convenience helper for checking if a semantically-known function returns unit.
#[allow(dead_code)]
fn _is_unit_return(report: &SemanticReport<'_>, name: &str) -> bool {
    report
        .signatures
        .iter()
        .find(|s| s.name == name)
        .map(|s| s.return_type == SemanticType::Unit)
        .unwrap_or(false)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::tlscript::{Lexer, ParallelHookAnalyzer, Parser, SemanticAnalyzer};

    fn parse_semantic_hooks(
        src: &str,
    ) -> (Module<'_>, SemanticReport<'_>, ParallelHookOutcome<'_>) {
        let mut parser = Parser::new(Lexer::new(src));
        let module = parser.parse_module().expect("parse ok");
        let mut sem_cfg = crate::tlscript::SemanticConfig::default();
        sem_cfg.external_call_allowlist = vec!["integrate".to_string(), "ui_button".to_string()];
        let semantic = SemanticAnalyzer::new(sem_cfg)
            .analyze(&module)
            .expect("semantic ok");
        let hooks = ParallelHookAnalyzer::new().analyze(&module, &semantic);
        (module, semantic, hooks)
    }

    #[test]
    fn suggests_parallel_contract_for_exported_serial_function() {
        let (module, semantic, hooks) = parse_semantic_hooks(concat!(
            "@export\n",
            "def solve_forces(dt: float):\n",
            "    integrate(dt)\n",
        ));
        let report = ParallelAdvisor::default().analyze(&module, &semantic, &hooks);
        let f = &report.functions[0];
        assert_eq!(f.status, ParallelAdvisoryStatus::SerialFallback);
        assert_eq!(
            f.fallback_reason,
            Some(ParallelFallbackReason::UnknownHostCalls)
        );
        assert!(f
            .suggestions
            .iter()
            .any(|s| matches!(s, ParallelAdvisorSuggestion::AddParallelContract { .. })));
        assert!(f.suggestions.iter().any(|s| matches!(s, ParallelAdvisorSuggestion::AnnotateHostCall { name, .. } if name == "integrate")));
    }

    #[test]
    fn suggests_main_thread_for_ui_calls() {
        let (module, semantic, hooks) =
            parse_semantic_hooks(concat!("@export\n", "def draw():\n", "    ui_button()\n",));
        let report = ParallelAdvisor::default().analyze(&module, &semantic, &hooks);
        let f = &report.functions[0];
        assert_eq!(
            f.fallback_reason,
            Some(ParallelFallbackReason::MainThreadHostCalls)
        );
        assert!(f
            .suggestions
            .iter()
            .any(|s| matches!(s, ParallelAdvisorSuggestion::AddMainThread)));
    }

    #[test]
    fn handles_parallel_auto_request_with_missing_contract() {
        let (module, semantic, hooks) = parse_semantic_hooks(concat!(
            "@export\n",
            "@parallel(auto)\n",
            "def tick():\n",
            "    let x: int = 1\n",
        ));
        let report = ParallelAdvisor::default().analyze(&module, &semantic, &hooks);
        let f = &report.functions[0];
        assert_eq!(
            f.fallback_reason,
            Some(ParallelFallbackReason::AutoParallelNeedsContract)
        );
        assert!(f
            .suggestions
            .iter()
            .any(|s| matches!(s, ParallelAdvisorSuggestion::ExpandAutoParallel { .. })));
    }

    #[test]
    fn recognizes_valid_parallel_hook_as_ready() {
        let (module, semantic, hooks) = parse_semantic_hooks(concat!(
            "@export\n",
            "@parallel(domain=\"bodies\", read=\"transform\", write=\"velocity\")\n",
            "def solve(dt: float):\n",
            "    let x: int = 1\n",
        ));
        let report = ParallelAdvisor::default().analyze(&module, &semantic, &hooks);
        assert_eq!(
            report.functions[0].status,
            ParallelAdvisoryStatus::ParallelReady
        );
        assert!(report.functions[0].fallback_reason.is_none());
    }

    #[test]
    fn report_exposes_summary_and_contract_templates() {
        let (module, semantic, hooks) = parse_semantic_hooks(concat!(
            "@export\n",
            "@parallel(auto)\n",
            "def tick():\n",
            "    let x: int = 1\n",
        ));
        let report = ParallelAdvisor::default().analyze(&module, &semantic, &hooks);
        let summary = report.summary_line();
        assert!(summary.contains("serial_fallback=1"));
        let templates = report.suggested_contract_templates();
        assert_eq!(templates.len(), 1);
        assert_eq!(templates[0].function, "tick");
        assert!(matches!(
            templates[0].source,
            ParallelContractTemplateSource::ExpandAutoParallel
        ));
        assert!(templates[0].decorator.starts_with("@parallel("));
    }
}
